package markbook;

import javax.swing.JOptionPane;

/**
 *
 * @author 334723103
 */
public class TeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public TeacherDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OutputDialog = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        markTable = new javax.swing.JTable();
        teacherName = new javax.swing.JLabel();
        courseName = new javax.swing.JLabel();
        teacherAction = new javax.swing.JComboBox<>();
        sortSelect = new javax.swing.JComboBox<>();
        coursePeriod = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmSort = new javax.swing.JButton();
        confirmOption = new javax.swing.JButton();
        periodOutput = new javax.swing.JLabel();
        teacherNum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        app = new javax.swing.JTextField();
        comm = new javax.swing.JTextField();
        tips = new javax.swing.JTextField();
        kuTotal = new javax.swing.JTextField();
        appTotal = new javax.swing.JTextField();
        commTotal = new javax.swing.JTextField();
        tipsTotal = new javax.swing.JTextField();
        weighting = new javax.swing.JTextField();
        stuNum = new javax.swing.JTextField();
        entry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addEntry = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        deleteID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        deleteEntry = new javax.swing.JTextField();
        confirmDelete = new javax.swing.JButton();
        ku = new javax.swing.JTextField();

        OutputDialog.setBackground(new java.awt.Color(255, 255, 255));
        OutputDialog.setForeground(new java.awt.Color(255, 255, 255));
        OutputDialog.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher's Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(829, 829));
        setResizable(false);

        markTable.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        markTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "AVERAGE"
            }
        ));
        markTable.setEnabled(false);
        jScrollPane1.setViewportView(markTable);
        if (markTable.getColumnModel().getColumnCount() > 0) {
            markTable.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        teacherName.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        teacherName.setText("SAMPLE NAME");

        courseName.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        courseName.setText("COURSE NAME");

        teacherAction.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        teacherAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Student", "Delete Student", "Add Entry", "Edit Entry", "Add Course", "Find Student" }));
        teacherAction.setMinimumSize(new java.awt.Dimension(132, 26));
        teacherAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionActionPerformed(evt);
            }
        });

        sortSelect.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        sortSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Increasing Mark", "Decreasing Mark" }));
        sortSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSelectActionPerformed(evt);
            }
        });

        coursePeriod.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        coursePeriod.setText("PERIOD");

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Sort By:");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Options:");

        confirmSort.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        confirmSort.setText("Confirm");
        confirmSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSortActionPerformed(evt);
            }
        });

        confirmOption.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        confirmOption.setText("Confirm");
        confirmOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmOptionActionPerformed(evt);
            }
        });

        periodOutput.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        periodOutput.setText("NUM");

        teacherNum.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        teacherNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherNum.setText("TEACHER NUM");

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel2.setText("Add Mark");

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel4.setText("K/U");

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel5.setText("APP");

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel6.setText("COMM");

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel7.setText("TIPS");

        app.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        comm.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        tips.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        kuTotal.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        appTotal.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        commTotal.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        tipsTotal.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        weighting.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        stuNum.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        entry.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel8.setText("Weighting:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel9.setText("Student ID:");

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel10.setText("Entry Name:");

        addEntry.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        addEntry.setText("Confirm");
        addEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel11.setText("Delete Entry");

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel12.setText("Student ID:");

        deleteID.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jLabel13.setText("Entry Name:");

        deleteEntry.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        deleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEntryActionPerformed(evt);
            }
        });

        confirmDelete.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        confirmDelete.setText("Confirm");
        confirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteActionPerformed(evt);
            }
        });

        ku.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmDelete)
                    .addComponent(deleteID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(deleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coursePeriod)
                                .addGap(18, 18, 18)
                                .addComponent(periodOutput)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherNum)
                            .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(kuTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                .addComponent(ku))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(appTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                .addComponent(app)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(commTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(comm))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tips, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(tipsTotal)))
                                    .addComponent(stuNum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weighting, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(confirmSort)
                                        .addGap(102, 102, 102)
                                        .addComponent(confirmOption))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel4)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel5)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(addEntry))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(sortSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(teacherAction, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(80, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(113, 113, 113))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coursePeriod)
                            .addComponent(periodOutput)
                            .addComponent(teacherNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(deleteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(deleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmDelete)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmSort)
                            .addComponent(confirmOption))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(app)
                            .addComponent(comm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kuTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weighting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stuNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEntry)
                        .addGap(268, 268, 268))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionActionPerformed

    }//GEN-LAST:event_teacherActionActionPerformed

    private void sortSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortSelectActionPerformed
        
    }//GEN-LAST:event_sortSelectActionPerformed

    private void confirmOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOptionActionPerformed
        Markbook book = new Markbook();
        int courseIndex = book.getCourse(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()));
        Course course = book.courses.get(courseIndex);
        if (this.teacherAction.getSelectedItem().toString().equals("Add Student")) {
            boolean success;
            String userID = JOptionPane.showInputDialog("Enter student number: ");
            success = book.addStudentToCourse(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()), Integer.parseInt(userID));
            if (success) {
                book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
                book.saveCourses();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error. Student not created.");
            }
        } else if (this.teacherAction.getSelectedItem().toString().equals("Delete Student")){
            boolean success;
            String userID = JOptionPane.showInputDialog("Enter student number: ");
            success = book.deleteStudent(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()), Integer.parseInt(userID));
            if (success) {
                book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
                book.saveCourses();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error. Student not deleted.");
            }
        } else if (this.teacherAction.getSelectedItem().toString().equals("Find Student")){ 
            String userID = JOptionPane.showInputDialog("Enter student number: ");
            int stuIndex = book.courses.get(courseIndex).checkStudent(Integer.parseInt(userID));
            if (stuIndex != -1) {
                book.courses.get(courseIndex).courseOutputStudent(Integer.parseInt(userID), userID);
            }
        } else if (this.teacherAction.getSelectedItem().toString().equals("Add Course")){ 
            String name = JOptionPane.showInputDialog("Enter course name: ");
            String period = JOptionPane.showInputDialog("Enter period number: ");
            if (book.addCourse(name, Integer.parseInt(period), Integer.parseInt(this.teacherNum.getText()))) {
                book.courses.get(book.courses.size()-1).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
            }
        }
    }//GEN-LAST:event_confirmOptionActionPerformed

    private void confirmSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSortActionPerformed
        String sortSelection = this.sortSelect.getSelectedItem().toString();
        Markbook book = new Markbook();
        int courseIndex = book.getCourse(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()));
        if (sortSelection.equals("Increasing Mark")) {
            book.courses.get(courseIndex).sortIncreasing();
            book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
            this.dispose();
        } else {
            book.courses.get(courseIndex).sortDecreasing();
            book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
            this.dispose();
        }
    }//GEN-LAST:event_confirmSortActionPerformed

    private void deleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEntryActionPerformed

    private void confirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteActionPerformed
        Markbook book = new Markbook();
        int studentID = Integer.parseInt(this.deleteID.getText());
        String entry = this.deleteEntry.getText();
        int courseIndex = book.getCourse(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()));
        boolean success = book.courses.get(courseIndex).deleteEntry(studentID, entry);
        if (success) {
            book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error. Entry not deleted.");
        }
    }//GEN-LAST:event_confirmDeleteActionPerformed

    private void addEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryActionPerformed
        Markbook book = new Markbook();
        int courseIndex = book.getCourse(this.courseName.getText(), Integer.parseInt(this.periodOutput.getText()));
        double[] entries = new double[4];
        entries[0] = Double.parseDouble(this.ku.getText());
        entries[1] = Double.parseDouble(this.app.getText());
        entries[2] = Double.parseDouble(this.comm.getText());
        entries[3] = Double.parseDouble(this.tips.getText());
        double[] totals = new double[4];
        totals[0] = Double.parseDouble(this.kuTotal.getText());
        totals[1] = Double.parseDouble(this.appTotal.getText());
        totals[2] = Double.parseDouble(this.commTotal.getText());
        totals[3] = Double.parseDouble(this.tipsTotal.getText());
        int weighting = Integer.parseInt(this.weighting.getText());
        String entryName = this.entry.getText();
        int studentNum = Integer.parseInt(this.stuNum.getText());
        String courseName = this.courseName.getText();
        int teacherNum = Integer.parseInt(this.teacherNum.getText());
        int period = Integer.parseInt(this.periodOutput.getText());
        book.addEntry(courseName, period, studentNum, entries[0], entries[1], entries[2], entries[3], totals[0], totals[1], totals[2], totals[3], weighting, entryName);
        book.courses.get(courseIndex).courseOutputTeacher(Integer.parseInt(this.teacherNum.getText()), this.teacherName.getText());
        this.dispose();
    }//GEN-LAST:event_addEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane OutputDialog;
    private javax.swing.JButton addEntry;
    private javax.swing.JTextField app;
    private javax.swing.JTextField appTotal;
    private javax.swing.JTextField comm;
    private javax.swing.JTextField commTotal;
    private javax.swing.JButton confirmDelete;
    private javax.swing.JButton confirmOption;
    private javax.swing.JButton confirmSort;
    public javax.swing.JLabel courseName;
    public javax.swing.JLabel coursePeriod;
    private javax.swing.JTextField deleteEntry;
    private javax.swing.JTextField deleteID;
    private javax.swing.JTextField entry;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ku;
    private javax.swing.JTextField kuTotal;
    public static javax.swing.JTable markTable;
    public javax.swing.JLabel periodOutput;
    public javax.swing.JComboBox<String> sortSelect;
    private javax.swing.JTextField stuNum;
    private javax.swing.JComboBox<String> teacherAction;
    public javax.swing.JLabel teacherName;
    public javax.swing.JLabel teacherNum;
    private javax.swing.JTextField tips;
    private javax.swing.JTextField tipsTotal;
    private javax.swing.JTextField weighting;
    // End of variables declaration//GEN-END:variables
}
